### ISSUE TITLE
Suggest software licenses

### ISSUE THREAD

**Issue by ddeboer** [CLARIAH/clariah-plus#104]
* Take stock of licenses currently being used by CLARIAH partners.
* Add a “The software SHOULD be licensed one of the … licenses clause: one of [popular licenses](https://opensource.org/licenses) EUPL.”

Ref #102.

**Comment by proycon** [comment]
@rsiebes spoke about an online license checker which we might want to link:

> online license compatibility checker: https://joinup.ec.europa.eu/collection/eupl/solution/joinup-licensing-assistant/jla-compatibility-checker ,  or as npm: https://www.npmjs.com/package/license-compatibility-checker
