### ISSUE TITLE
Generic infrastructure requirements

### ISSUE THREAD

**Issue by ddeboer** [CLARIAH/clariah-plus#15]
Netwerk Digitaal Erfgoed (NDE) develops web applications (‘netwerkdiensten’) including HTTP APIs and demonstrators. These applications currently run on [our Kubernetes cluster](https://github.com/netwerk-digitaal-erfgoed/infrastructure) but will be moved to other organisations for hosting in the long run. We’re in the process of formalising [application infrastructure requirements](https://github.com/netwerk-digitaal-erfgoed/requirements-infrastructure) that we will use when discussing application handover. (Unlike many of the CLARIAH use cases, these requirements are not aimed at solving research questions.)

These requirements follow best practices such as [Twelve-Factor](https://12factor.net) and [infrastructure as code](https://en.wikipedia.org/wiki/Infrastructure_as_code). Additional principles are:

- A clear **boundary** between the application and the infrastructure it runs on. The application code should not contain infrastructure specifics and be as generic as possible so instances can be hosted by multiple parties, including developers that want to run or debug the application locally. On the other hand, existing infrastructure should not have to change fundamentally to accommodate new applications.
- Processes are **automated**, which strengthens transparency and prevents human error; for example application code is built automatically when commits are pushed.
- The infrastructure is **reliable**, which helps adoption of the applications.

### Questions

1. Should I create a use case among many for this, for instance ‘Serving web applications’? 
2. Do we have a place for generic infrastructure (i.e. non application-specific) best practices?
3. Can we work together towards a single set of requirements or are the participating organisations’ situations too different?

**Comment by proycon** [comment]
Closing this because this is now well underway in #4 and #5
