### ISSUE TITLE
[IG Annotation] Defining user needs for annotation support

### ISSUE THREAD

**Issue by marijnkoolen** [CLARIAH/clariah-plus#21]
I've started a document on [user needs for manual annotation support](https://github.com/CLARIAH/IG-Annotation/blob/master/docs/annotation-needs.md), which is copied from earlier documents we wrote with o.a. @lilimelgar and @jblom. 

This is also based on how @jauco described his idea of the IGs: focus on two or three technical use cases that each groups chooses to focus on. The ones I picked are based on things we've been working on since CLARIAH Core, but of course this is all up for discussion.

**Comment by proycon** [comment]
Clsoing this, this IG never took off.
