### ISSUE TITLE
Define cross-WP team for tool discovery

### ISSUE THREAD

**Issue by proycon** [CLARIAH/clariah-plus#30]
We need to identify people who want to work on this core-shared service.

It is important we have representation from Ineo, from WP4 (vocabularies), from WP3 (existing codemeta & CMDI initiatives)

The current composition of this team can be found here: https://github.com/orgs/CLARIAH/teams/fair-tool-discovery

**Comment by proycon** [comment]
Please simply add a comment with the role you'd like to fulfill in this shared core:

I'm probably coordinating this, and will if needed also act as a main developer for software components (like the harvester and tool registry). I've worked with codemeta and in WP3 we have some CMDI profiles for software metadata from earlier projects, that may serve as inspiration for the vocabulary.

**Comment by roelandordelman** [comment]
please add me as stakeholder ;)

**Comment by proycon** [comment]
I received an expression of interest to participate from @JanOdijk  and I mailed Sebastiaan Fluitsma about possible participation from Ineo's side.

**Comment by ErwinKomen** [comment]
> The current composition of this team can be found here: https://github.com/orgs/CLARIAH/teams/fair-tool-discovery

Link not existing?

**Comment by jblom** [comment]
@proycon want to be part of this. Mostly I need to tackle, which of the WP5 tools can be moved to a public repository and, if not, what can be done to extract parts of the code that can be made public. 

Would also like to help review & test code.

**Comment by JessedeDoes** [comment]
You can add me as representing INT, in order to make sure our software gets properly codemeta'd.

**Comment by 4tikhonov** [comment]
Hi @proycon, please add me as contact person for DANS software codemeta.

**Comment by ddeboer** [comment]
@proycon You can add me to the team too.

**Comment by proycon** [comment]
@jblom @JessedeDoes @4tikhonov @ddeboer Thanks! I added you to the team. 

I'm not immediately planning any meetings or anything (they tend to be overrated and time-consuming imho), I hope we can just bootstrap ourselves from the issues mostly. So please don't hold back and provide your input wherever you see fit.

**Comment by proycon** [comment]
> Link not existing?

@erwinkomen it does exist.. but perhaps it's not accessible to people not in the CLARIAH github organization yet (so that kind of defeats the purpose of the link).

**Comment by proycon** [comment]
@ErwinKomen In case you're interested in joining in, just reply here (or in any of the other corresponding issues for the other tracks if you want in on those.

**Comment by proycon** [comment]
@rlzijdeman We don't have any 'official' representation from WP4 yet in our tool discovery group, but considering the linked data nature this would be very welcome. Do you have any volunteers (or can you appoint one ;) )?
