### ISSUE TITLE
Compose and publish metadata for all software/services, for tool discovery

### ISSUE THREAD

**Issue by proycon** [CLARIAH/clariah-plus#38]
All CLARIAH software/services should provide metadata in the agreed upon form (will be specified as part of the [Software Requirements](https://github.com/CLARIAH/clariah-plus/issues/4)), it's most likely going to be the requirement to include a ``codemeta.json`` file in the root of the source code repository, and OpenAPI or other dedicated endpoints for webservices.

This task is one that is spread over all CLARIAH partners/institutions and this issue may track general progress.

**Comment by ddeboer** [comment]
#40

**Comment by proycon** [comment]
The first step (or last, depending on how you look at it) in composing publishing software metadata and making it harvestable, is registering the software with the tool source registry, that is being tracked in #91

**Comment by proycon** [comment]
Closing, succeeded by https://github.com/CLARIAH/clariah-plus/issues/143
