### ISSUE TITLE
Document 'software metadata requirements'

### ISSUE THREAD

**Issue by proycon** [CLARIAH/clariah-plus#40]
As part of the software & infrastructure requirements, we already formulated a clause stating the requirement to deliver software metadata. The actual metadata requirements, however, may need to be worked out in a separate document (because of length), and we can then refer to that from the software & infrastructure requirements.

This would be a main deliverable of this tool discovery track.

**Comment by ddeboer** [comment]
Practically, a `codemeta.json` must be supplied. The requirements should explain which CodeMeta properties are required.

**Comment by proycon** [comment]
Assessment procedures for extra vocabulary things like TLR and SLR (#32) should be explicitly part of these requirements.

**Comment by ddeboer** [comment]
See also https://github.com/Dans-labs/dariah-contrib/wiki/Assessment-criteria-'Services', as suggested by @femmynine.

**Comment by proycon** [comment]
The document on software metadata requirements is fairly complete now, though small things may still change if needed. Closing this issue.

**Comment by proycon** [comment]
It was decided in the Tech Committee today that we will finalize the software metadata requirements (and by extension the vocabulary discussion of #32) the upcoming techday (2022-10-27).
