### ISSUE TITLE
Implement codemeta validation component for tool discovery, against clariah requirements

### ISSUE THREAD

**Issue by proycon** [CLARIAH/clariah-plus#50]
The following was already suggested by @ddeboer in #32.

> Create a SHACL shape to validate CLARIAH-specific codemeta.json files.

This sounds good to me and would be a valuable component that can be invoked from the harvester (#33).
@ddeboer Is this something you'd want to take up implementing? (I don't have prior expertise with SHACL myself so having that would be a plus).

**Comment by ddeboer** [comment]
Sure! Do we want the SHACL in this repository or separately? And if the latter, where?

**Comment by proycon** [comment]
> Sure! Do we want the SHACL in this repository or separately? And if the latter, where?

In a separate one yes, perhaps we can use [CLARIAH/tool-discovery](https://github.com/CLARIAH/tool-discovery) for that?

> I suggest to combine this issue with #32: we can use SHACL for both the ontology definition and the validation rules. This is 
> more efficient and maintainable than adding OWL just for the ontology. For more on this approach, see 
> https://www.topquadrant.com/shacl-blog/. An example is the NDE Dataset requirements, which use SHACL only.

This validation issue is indeed very closely related to #32, so combining them as much as possible would make sense. The approach you propose looks interesting.

As I mentioned earlier; #32 has two aspects: 1) the CLARIAH-specific vocabulary and 2) the generic vocabulary that is currently missing from codemeta/schema.org but we need for expressing certain aspects of metadata. The latter issue is being discussed in codemeta/codemeta#271 and we seem on the verge of forming a small 'task force' for that in a separate repository (wider than CLARIAH) with the intention to eventually merge it into codemeta if the community there agrees. You're welcome to join in there too of course so we can align all these components properly.
