### ISSUE TITLE
Set up basic hardware infrastructure for Clariah services and research

### ISSUE THREAD

**Issue by mmisworking** [CLARIAH/clariah-plus#83]

**Comment by mmisworking** [comment]
Hardware is stored at a certified datacenter in Amsterdam

**Comment by mmisworking** [comment]
Review cluster installation by consultant on 21st of June

**Comment by proycon** [comment]
@mmisworking Does this mean the hardware is installed and available now?

**Comment by mmisworking** [comment]
Hardware is installed and Nutanix (and harvesterHCI) is up and running. We are now working on the IaC to accommodate the new Kubernetes clusters en proxy solutions. We want to have it working from the IaC point of view. If you want to change/test something if production services are already running it is harder to do. We can't buy a second hardware solution for testing purposes. We will post every week the progress in this task.

**Comment by proycon** [comment]
@mmisworking I think we can close this now as the hardware is available and running?
