### ISSUE TITLE
Extract software metadata from the web (service endpoints and/or webpages)

### ISSUE THREAD

**Issue by proycon** [CLARIAH/clariah-plus#92]
The harvesting pipeline that is being implemented currently (#33) is set up in such a way that the source-code is always the most authoritative place for holding software metadata descriptions.

However, there is a distinction between the software source code and *service instances* of that software, and the latter may add some metadata that is not applicable to the source as such. Instances are hosted on a particular URL and may have particular access limitations. We want to make that distinction explicit.

In the *tool source registry* for the harvester, we therefore provide the link to the source code alongside the web endpoints. The harvester first queries the source code repositories and converts the metadata in there  to schema.org/codemeta's `@SoftwareSourceCode`, then it queries the web endpoints and enriches the metadata in the way proposed in codemeta/codemeta#271 .

How can websites and webservices provide metadata? I want to support the following for the harvester pipeline:

* [x] Support inline schema.org metadata in a ``<script type="application/ld+json">`` block, with `@type` any subclass of `schema:SoftwareApplication` or any of the other ones proposed in codemeta/codemeta#271, including  `schema:WebAPI` and `schema:WebPage`. 
    * This is the most explicit form to provide metadata and the only one that ensures that all metadata ends up in the harvested end-product.
    * See also https://developers.google.com/search/docs/advanced/structured-data/sd-policies 
    * Support for microdata wil be deferred to a later stage (https://schema.org/docs/gs.html)
* [x] Support for webservices providing an OpenAPI specification (in json or yaml), parse and convert at least the "Info" block to codemeta.
* [x] Support for the fallback option: parse certain `meta` tags in the HTML `head`

**Comment by proycon** [comment]
It may be worth identifying if there are already CLARIAH services and websites that make their tool metadata available in other ways that may be harvestable (i.e. published by the web endpoint itself, not some other higher-order registry). An important example currently is CLAM, widely used for WP3 webservices and outputting metadata in its own XML format; I will make that output an OpenAPI Info block too (proycon/clam#32).

Please comment if you can answer what metadata descriptions certain CLARIAH partners are currently using?

**Comment by ddeboer** [comment]
Should the _type_ of service be documented with the software and/or be derived from the service definition as it is retrieved over HTTP by the harvester? Example: the fact that software `x` has an OpenAPI endpoint available at URL `y` and s SPARQL endpoint at URL `z`.
