### ISSUE TITLE
Add B&G datasets to the NDE dataset register

### ISSUE THREAD

**Issue by wmelder** [CLARIAH/clariah-plus#96]
Provide the relevant datasets from the [B&G data catalog](https://data.beeldengeluid.nl/id/datacatalog/0001) to the NDE dataset register using the [dataset API](https://datasetregister.netwerkdigitaalerfgoed.nl/api/static/index.html#/default/post_datasets). This way Clariah+ doesn't need to provide custom method to import the B&G datasets information.
See issue #56

**Comment by menzowindhouwer** [comment]
Yes, CL+ will harvest B&G via the NDE triplestore.

**Comment by wmelder** [comment]
- [x] fixed content negotiation
- [ ] fix multiple language strings for sdo:description don't comply with NDE /datasets/validate

**Comment by wmelder** [comment]
datasets can be found [here](https://datasetregister.netwerkdigitaalerfgoed.nl/search.php)
this page provides a SPARQL [query and link to the triple store](https://triplestore.netwerkdigitaalerfgoed.nl/sparql?query=PREFIX%20dcat:%20%3Chttp:%2F%2Fwww.w3.org%2Fns%2Fdcat%23%3E%0APREFIX%20dct:%20%3Chttp:%2F%2Fpurl.org%2Fdc%2Fterms%2F%3E%0A%0ASELECT%20DISTINCT%20%3Fdataset%20%3Ftitle%20WHERE%20%7B%0A%20%20%3Fdataset%20a%20dcat:Dataset%20.%0A%20%20%3Fdataset%20dct:title%20%3Ftitle%20.%0A%20%20FILTER(LANG(%3Ftitle)%20%3D%20%22%22%20%7C%7C%20LANGMATCHES(LANG(%3Ftitle),%20%22nl%22))%20%0A%20%20%3Fdataset%20dct:publisher%20%3Chttps:%2F%2Fwww.beeldengeluid.nl%3E%20.%0A%7D), but that didn't seem to work (yet).
Maybe some in between steps are not finished yet.

**Comment by ddeboer** [comment]
> this page provides a SPARQL [query and link to the triple store](https://triplestore.netwerkdigitaalerfgoed.nl/sparql?query=PREFIX%20dcat:%20%3Chttp:%2F%2Fwww.w3.org%2Fns%2Fdcat%23%3E%0APREFIX%20dct:%20%3Chttp:%2F%2Fpurl.org%2Fdc%2Fterms%2F%3E%0A%0ASELECT%20DISTINCT%20%3Fdataset%20%3Ftitle%20WHERE%20%7B%0A%20%20%3Fdataset%20a%20dcat:Dataset%20.%0A%20%20%3Fdataset%20dct:title%20%3Ftitle%20.%0A%20%20FILTER(LANG(%3Ftitle)%20%3D%20%22%22%20%7C%7C%20LANGMATCHES(LANG(%3Ftitle),%20%22nl%22))%20%0A%20%20%3Fdataset%20dct:publisher%20%3Chttps:%2F%2Fwww.beeldengeluid.nl%3E%20.%0A%7D), but that didn't seem to work (yet).

@wmelder I see 9 datasets now. Did you expect more?

**Comment by ddeboer** [comment]
> @ddeboer I still see no results in the triple store. 

Did you click the ‘Run’ button in the web interface?

> But indeed, [Muziekweb](http://data.beeldengeluid.nl/id/dataset/0026) has publisher https://www.muziekweb.nl/ The other set that is missing is [Natuurbeelden](http://data.beeldengeluid.nl/id/dataset/0003) that has publisher https://natuurbeelden.openbeelden.nl/. Both datasets also have B&G as publisher. Maybe that is a problem?

Not a problem as such, but the Requirements for Datasets only [allow a single `schema:publisher`](https://netwerk-digitaal-erfgoed.github.io/requirements-datasets/#dataset-overview). This is on purpose: usually it’s really a single organisation that takes care of _publishing_ the dataset.

You can indicate other collaborating parties with `schema:creator`. Would that solve your problem?

**Comment by wmelder** [comment]
>Did you click the ‘Run’ button in the web interface?

Yes, but it keeps telling me that there are no results.

>Not a problem as such, but the Requirements for Datasets only [allow a single schema:publisher](https://netwerk-digitaal-erfgoed.github.io/requirements-datasets/#dataset-overview). This is on purpose: usually it’s really a single organisation that takes care of publishing the dataset. Apparently the SPARQL query happened to pick out the organisation other than BenG in these two cases. After all, RDF guarantees no order for collections.

O indeed. I missed that. So I will mark this as an additional test before publishing. It didn't came out of the SHACL API validation by the way.

>You can indicate other collaborating parties with schema:creator. Would that solve your problem?

That's a good suggestion indeed.

**Comment by wmelder** [comment]
When I re-register these datasets via the API (POST), will the datasets be overwritten?

**Comment by ddeboer** [comment]
> O indeed. I missed that. So I will mark this as an additional test before publishing. It didn't came out of the SHACL API validation by the way.

When I query the dataset manually, the RDF contains only a single publisher:


```
comunica-sparql  https://data.beeldengeluid.nl/id/dataset/0026  'select * {?s ?p ?o} limit 1000'
[
{"s":"http://data.beeldengeluid.nl/id/dataset/0026","p":"https://schema.org/description","o":"\"Muziekweb is de muziekbibliotheek van Nederland. Ons doel is om muziek en de informatie over muziek voor iedereen laagdrempelig aan te bieden. Muziekweb heeft sinds 1961 een collectie opgebouwd van 600.000 cd’s, 300.000 lp’s en 30.000 muziek-dvd’s (dat is samen goed voor zo'n zeven miljoen tracks!). De site is een bron van informatie over muziek die de afgelopen vijftig jaar in Nederland is uitgebracht, en een ideale plek om meer muziek te leren kennen. Deze dataset beschikt over de laatste linked data versie van het muziekweb. Hier vind je een linked data view waarin alle albums van het muziekweb zijn weergegeven.\"@nl"},
{"s":"http://data.beeldengeluid.nl/id/dataset/0026","p":"https://schema.org/distribution","o":"http://data.beeldengeluid.nl/id/datadownload/0025"},
{"s":"http://data.beeldengeluid.nl/id/dataset/0026","p":"https://schema.org/inLanguage","o":"\"nl-NL\""},
{"s":"http://data.beeldengeluid.nl/id/dataset/0026","p":"https://schema.org/includedInDataCatalog","o":"http://data.beeldengeluid.nl/id/datacatalog/0001"},
{"s":"http://data.beeldengeluid.nl/id/dataset/0026","p":"https://schema.org/license","o":"https://opendatacommons.org/licenses/by/"},
{"s":"http://data.beeldengeluid.nl/id/dataset/0026","p":"https://schema.org/mainEntityOfPage","o":"https://data.muziekweb.nl/"},
{"s":"http://data.beeldengeluid.nl/id/dataset/0026","p":"https://schema.org/name","o":"\"Muziekweb\"@nl"},
{"s":"http://data.beeldengeluid.nl/id/dataset/0026","p":"https://schema.org/publisher","o":"https://www.muziekweb.nl/"},
{"s":"http://data.beeldengeluid.nl/id/dataset/0026","p":"http://www.w3.org/1999/02/22-rdf-syntax-ns#type","o":"https://schema.org/Dataset"},
{"s":"http://data.beeldengeluid.nl/id/datadownload/0025","p":"https://schema.org/description","o":"\"Bevraag Muziekweb via SPARQL.\"@nl"},
{"s":"http://data.beeldengeluid.nl/id/datadownload/0025","p":"https://schema.org/inLanguage","o":"\"nl-NL\""},
{"s":"http://data.beeldengeluid.nl/id/datadownload/0025","p":"https://schema.org/license","o":"https://opendatacommons.org/licenses/by/"},
{"s":"http://data.beeldengeluid.nl/id/datadownload/0025","p":"https://schema.org/name","o":"\"Muziekweb als linked data\"@nl"},
{"s":"http://data.beeldengeluid.nl/id/datadownload/0025","p":"http://www.w3.org/1999/02/22-rdf-syntax-ns#type","o":"https://schema.org/DataDownload"},
{"s":"http://data.beeldengeluid.nl/id/datadownload/0025","p":"https://schema.org/contentSize","o":"\"930000\""},
{"s":"http://data.beeldengeluid.nl/id/datadownload/0025","p":"https://schema.org/contentUrl","o":"https://api.data.muziekweb.nl/datasets/MuziekwebOrganization/Muziekweb/services/Muziekweb/sparql"},
{"s":"http://data.beeldengeluid.nl/id/datadownload/0025","p":"https://schema.org/encodingFormat","o":"\"application/sparql-query\""},
{"s":"http://data.beeldengeluid.nl/id/datadownload/0025","p":"https://schema.org/usageInfo","o":"https://www.w3.org/TR/rdf-sparql-query/"},
{"s":"https://www.muziekweb.nl/","p":"https://schema.org/name","o":"\"Muziekweb\"@nl"},
{"s":"https://www.muziekweb.nl/","p":"http://www.w3.org/1999/02/22-rdf-syntax-ns#type","o":"https://schema.org/Organization"},
{"s":"https://www.muziekweb.nl/","p":"https://schema.org/sameAs","o":"http://www.wikidata.org/entity/Q18088607"}
]
```

> When I re-register these datasets via the API (POST), will the datasets be overwritten?

Yep. Or wait a day and they should be crawled again. 😄

**Comment by wmelder** [comment]
All datasets have b&g as publisher now
